# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=b'', max_length=255)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=255)),
                ('parameters', models.TextField(default=b'')),
                ('result', models.TextField(default=b'')),
                ('status', models.CharField(choices=[(b'open', b'Open'), (b'in_progress', b'In progress'), (b'done', b'Done'), (b'error', b'Error')], default=b'open', max_length=50)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urad_api.Job')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(default=b'', max_length=255)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
